In [1]:
import numpy as np
r=np.arange(1,9,2)
r

array([1, 3, 5, 7])

In [2]:
r.reshape(-2,2)

array([[1, 3],
       [5, 7]])

In [3]:
r.ravel()

array([1, 3, 5, 7])

In [4]:
r=np.linspace(0,10,5)
r

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [5]:
mat=np.arange(9).reshape((3,3))
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
mat[1,1]

4

In [7]:
mat[1,]

array([3, 4, 5])

In [8]:
mat[1]

array([3, 4, 5])

In [9]:
for row in mat:
    print(row)

[0 1 2]
[3 4 5]
[6 7 8]


In [10]:
for v in np.nditer(mat):
    print(v)

0
1
2
3
4
5
6
7
8


In [11]:
map=np.arange(9).reshape(3,3)
map

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
index=map>3
index

array([[False, False, False],
       [False,  True,  True],
       [ True,  True,  True]])

In [13]:
map[index]

array([4, 5, 6, 7, 8])

In [14]:
map[map>3]

array([4, 5, 6, 7, 8])

In [15]:
map[(map>3) | (map<1)]

array([0, 4, 5, 6, 7, 8])

In [16]:
a=np.array([[1,0],[2,-1]])
b=np.array([[1,1],[0,-1]])

In [17]:
a

array([[ 1,  0],
       [ 2, -1]])

In [18]:
b

array([[ 1,  1],
       [ 0, -1]])

In [19]:
a@b

array([[1, 1],
       [2, 3]])

In [20]:
a*b

array([[1, 0],
       [0, 1]])

In [24]:
import pandas as pd
c=pd.Series([4,3,2],index=range(2,5))
c

2    4
3    3
4    2
dtype: int64

In [25]:
c+1

2    5
3    4
4    3
dtype: int64

In [27]:
d=pd.Series([-1,2,np.nan,4,5])
d

0   -1.0
1    2.0
2    NaN
3    4.0
4    5.0
dtype: float64

In [28]:
d[:2]

0   -1.0
1    2.0
dtype: float64

In [29]:
d[d<3]

0   -1.0
1    2.0
dtype: float64

In [30]:
d+1

0    0.0
1    3.0
2    NaN
3    5.0
4    6.0
dtype: float64

In [31]:
d**2

0     1.0
1     4.0
2     NaN
3    16.0
4    25.0
dtype: float64

In [32]:
d.index

RangeIndex(start=0, stop=5, step=1)

In [38]:
g=pd.Series(['apple','pen','pen','apple','pen'],dtype='category')

In [39]:
g.cat.categories

Index(['apple', 'pen'], dtype='object')

In [40]:
df=pd.DataFrame({'a':[1,2,3],'b':[2,4,6],'c':[1,6,9]})

In [47]:
df

a  b  c
0  1  2  1
1  2  4  6
2  3  6  9

In [41]:
df.iloc[2,1]

6

In [43]:
df.where(df.a != 2)

a    b    c
0  1.0  2.0  1.0
1  NaN  NaN  NaN
2  3.0  6.0  9.0

In [44]:
df.a

0    1
1    2
2    3
Name: a, dtype: int64

In [45]:
df.a !=2

0     True
1    False
2     True
Name: a, dtype: bool

In [46]:
df[~(df.a == 2)]

a  b  c
0  1  2  1
2  3  6  9

In [49]:
df.filter(items=['a','b'])

a  b
0  1  2
1  2  4
2  3  6

In [52]:
df.filter(items=['0','1'],axis=0)

Empty DataFrame
Columns: [a, b, c]
Index: []

In [78]:
import nltk

In [79]:
nltk.download()

showing info https://raw.githubusercontent.com/nltk/nltk_data/gh-pages/index.xml


True

In [80]:
sw=set(nltk.corpus.stopwords.words('english'))
print("Stopwords", list(sw)[:7])

Stopwords ['be', 'do', "that'll", "needn't", 'them', 'its', 'each']


In [81]:
#Gutenburg Corpus
gb=nltk.corpus.gutenberg
print('Gutenberg files', gb.fileids()[-5:])

Gutenberg files ['milton-paradise.txt', 'shakespeare-caesar.txt', 'shakespeare-hamlet.txt', 'shakespeare-macbeth.txt', 'whitman-leaves.txt']


In [89]:
#filtering a couple of sentences from the book shakespeare-caesar.txt
text=gb.sents('shakespeare-caesar.txt')[:4]
print(text)

[['[', 'The', 'Tragedie', 'of', 'Julius', 'Caesar', 'by', 'William', 'Shakespeare', '1599', ']'], ['Actus', 'Primus', '.'], ['Scoena', 'Prima', '.'], ['Enter', 'Flauius', ',', 'Murellus', ',', 'and', 'certaine', 'Commoners', 'ouer', 'the', 'Stage', '.']]


In [100]:
#filter stopwords
filtered=[]
for t in text:
    for w in t:
        if w.lower() not in sw:
            filtered.append(w)
                    

In [101]:
filtered

['[',
 'Tragedie',
 'Julius',
 'Caesar',
 'William',
 'Shakespeare',
 '1599',
 ']',
 'Actus',
 'Primus',
 '.',
 'Scoena',
 'Prima',
 '.',
 'Enter',
 'Flauius',
 ',',
 'Murellus',
 ',',
 'certaine',
 'Commoners',
 'ouer',
 'Stage',
 '.']

In [102]:
tagged=nltk.pos_tag(filtered)
print(tagged)

[('[', 'NN'), ('Tragedie', 'NNP'), ('Julius', 'NNP'), ('Caesar', 'NNP'), ('William', 'NNP'), ('Shakespeare', 'NNP'), ('1599', 'CD'), (']', 'NNP'), ('Actus', 'NNP'), ('Primus', 'NNP'), ('.', '.'), ('Scoena', 'NNP'), ('Prima', 'NNP'), ('.', '.'), ('Enter', 'NNP'), ('Flauius', 'NNP'), (',', ','), ('Murellus', 'NNP'), (',', ','), ('certaine', 'NN'), ('Commoners', 'NNP'), ('ouer', 'NN'), ('Stage', 'NNP'), ('.', '.')]


In [110]:
lowercase_words = [word.lower() for word in filtered]
print(lowercase_words)

['[', 'tragedie', 'julius', 'caesar', 'william', 'shakespeare', '1599', ']', 'actus', 'primus', '.', 'scoena', 'prima', '.', 'enter', 'flauius', ',', 'murellus', ',', 'certaine', 'commoners', 'ouer', 'stage', '.']


In [111]:
lw=nltk.pos_tag(lowercase_words)
print(lw)

[('[', 'NN'), ('tragedie', 'NN'), ('julius', 'NN'), ('caesar', 'NN'), ('william', 'NN'), ('shakespeare', 'NN'), ('1599', 'CD'), (']', 'NN'), ('actus', 'NN'), ('primus', 'NN'), ('.', '.'), ('scoena', 'JJ'), ('prima', 'NN'), ('.', '.'), ('enter', 'NN'), ('flauius', 'NN'), (',', ','), ('murellus', 'NN'), (',', ','), ('certaine', 'NN'), ('commoners', 'NNS'), ('ouer', 'VBP'), ('stage', 'NN'), ('.', '.')]


In [113]:
#remove words with NNP and CD values
words=[]
for word in lw:
 if word[1] != 'NNP' and word[1] != 'CD':
    words.append(word[0]) 

print(words)

['[', 'tragedie', 'julius', 'caesar', 'william', 'shakespeare', ']', 'actus', 'primus', '.', 'scoena', 'prima', '.', 'enter', 'flauius', ',', 'murellus', ',', 'certaine', 'commoners', 'ouer', 'stage', '.']


In [114]:
#Bag of Word Model
hamlet=gb.raw('shakespeare-hamlet.txt')
macbeth=gb.raw('shakespeare-macbeth.txt')

In [119]:
from sklearn.feature_extraction.text import CountVectorizer
#Create the feature vector by omitting English stopwords
cv = CountVectorizer(stop_words='english')
print("Feature vector", cv.fit_transform([hamlet, 
macbeth]).toarray())
#selection of the features (unique words) 
print("Features", cv.get_feature_names_out()[:5])



Feature vector [[ 1  0  1 ... 14  0  1]
 [ 0  1  0 ...  1  1  0]]
Features ['1599' '1603' 'abhominably' 'abhorred' 'abide']


In [134]:
import string
#Analyzing word frequencies
punctuation = set(string.punctuation)
filtered = [w.lower() for w in words if w.lower() not in sw and 
w.lower() not in punctuation]


In [136]:
from nltk.probability import FreqDist
fd=FreqDist(filtered)
print(fd)


<FreqDist with 16 samples and 16 outcomes>


In [140]:
print("Most common words:")
for word, frequency in fd.most_common():
    print(f"{word}: {frequency}")

Most common words:
tragedie: 1
julius: 1
caesar: 1
william: 1
shakespeare: 1
actus: 1
primus: 1
scoena: 1
prima: 1
enter: 1
flauius: 1
murellus: 1
certaine: 1
commoners: 1
ouer: 1
stage: 1


In [145]:
bigram_freq=FreqDist(filtered)
print(bigram_freq)

<FreqDist with 16 samples and 16 outcomes>


In [146]:
bigram_freq.most_common(5)

[('tragedie', 1),
 ('julius', 1),
 ('caesar', 1),
 ('william', 1),
 ('shakespeare', 1)]

In [ ]:
# One function to remove punctuation, tokenize, remove stopwords and stem
def clean_text(text):

    text = re.sub(r"what's", "what is ", text)
    text = re.sub(r"\'s", " ", text)

    text = re.sub(r"\'ve", " have ", text)

    text = re.sub(r"can't", "cannot ", text)

    text = re.sub(r"n't", " not ", text)

    text = re.sub(r"I'm", "i am ", text)

    text = re.sub(r"i'm", "i am ", text)

    text = re.sub(r"\'re", " are ", text)

    text = re.sub(r"\'d", " would ", text)

    text = re.sub(r"\'ll", " will ", text)

    text = re.sub(r"\'scuse", " excuse ", text)
    
    text = "".join([word.lower() for word in text if word not in string.punctuation])
     
    tokens = re.split('\W+', text)

    #words = [wn.lemmatize(word, 'v') for word in tokens]

    text = [ps.stem(word) for word in tokens if word not in stopwords]

    text = [wn.lemmatize(word) for word in text] 
    
    text = " ".join(text)
    
    return text